version: "3.5"

services:
    frontend:
        build: ./ml-kurkkumopo-frontend
        ports:
            - 3000:3000
    
    backend:
        build: ./ml-kurkkumopo-backend
        ports:
            - 5000:5000
        volumes: 
            - models:/src/model
        
    training:
        build: ./ml-kurkkumopo-training
        volumes: 
            - models:/src/model
            - imgs:/src/imgs

volumes:
    models:
    imgs:
    