version: '3.5'

services:

    frontend:
        build: ./frontend-example-docker
        ports: 
            - 5000:5000
        environment: 
            - API_URL=http://localhost:8000
    
    backend:
        build: ./backend-example-docker
        ports: 
            - 8000:8000
        environment: 
            - FRONT_URL=http://localhost:5000
            - REDIS=redis-cache
            - DB_USERNAME=example
            - DB_PASSWORD=example
            - DB_HOST=db

    redis-cache:
        image: redis
        ports:
            - 6379:6379

    reverse-proxy:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            
    db:
        image: postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_USER=example
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=example      
